### PR TITLE
Fix paths

### PR DESCRIPTION
**Pull request by mandreko**
I was trying out some of the persistence modules, and ran into some issues. Here are the fixes I made to get them to work properly.

### CODE REVIEW

**Comment by Und3rf10w** [comment]
Thank you so much for this. I never really got around to bugfixing the rest of the persistence modules. I was literally going to take a whack at the ADS one today.

I'll merge this now!

Why opt for ```HKCU``` instead of ```HKLM```?

**Comment by mandreko** [comment]
In the documentation I saw for this module it said that admin was not required. That appealed to me as my assessment has an unprivileged user who could not write to HKLM. 

I agree that it could be extended to try writing to HKLM first before HKCU, or just prompt in cobalt strike for a decision. I just didn't get there yet.

**Comment by Und3rf10w** [comment]
Excellent, I'm testing some changes with this merge that'll detect whether the user has admin or not and determine whether to write to ```HKLM``` or ```HKCU```

**Comment by Und3rf10w** [comment]
Please see commit 127b128 for added keyhive detection. This is based on whether or not Cobalt strike sees the beacon as an admin session or not (red lighting bolts and ```*``` at the end of the username)

**Pull request merged**
